---
title: 'Introduction'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is multi-dimensional media?
- What does the FAIR principles refer to?
- What type of infrastructure are available
for collaborative research and using 
linking multi-dimensional data over the web?
- What do I need to do if I want to create 
stories with my own multi-dimensional linked data?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- To understand multidimensional data, including how data is stored
in various types of files.
- To be aware of what the FAIR principles are.
- To understand how Uniform Resource Locator allow to query webpages
as well as more structured information.
- To get experience using a Virtual Research Environment.

::::::::::::::::::::::::::::::::::::::::::::::::

The lesson aims to support better understanding of multidimensional media 
available over the web which might serve various educational, research,
as well as storytelling and audience engagement processes.

The lesson focuses on stories in the fields of visual and 
material culture within Higher Education, Galleries, Libraries, A
rchives, Museums (GLAMs), as well as the creative industries. Hence, it
containes many examples and websites in this area. Howver,
many concepts are cross-disciplinary and can be applied
to other areas as well as sectors.




