---
title: 'Retrieving and Curating Multidimensional Data'
teaching: 2.5
exercises: 2
---

We will curate a dataset of multidimensional data
to practice what we learnt.


We will make use of the VRE 
to store, collaborate and provide access to the dataset.

:::::::::: challenge

## Challenge: Curating dataset
In teams of 2-3 choose a theme to retrieve and
curate the dataset. 

The theme can be either a project you are developing,
or you can choose one 
from the ones describe below.

If you have selected a theme in previous 
sessions, e.g. [previous tutorial](https://universityofbrighton.github.io/2023-exhibition-design),
you can continue working on this.

Search for a minimum of 5-6 images, a video and a 3D image/model.
Downloaded them and upload to a share folder in the VRE.
Take care of your resolution, filenames, and recording the metadata
of the files.

:::::::::: 

## Digital storytelling suggested themes

### Industrial heritage 

**Stories**: 
[https://www.europeana.eu/en/stories?tags=industrial-heritage&page=1](https://www.europeana.eu/en/stories?tags=industrial-heritage&page=1) 
 
**Images**: 
[https://www.europeana.eu/en/search?page=1&qf=collection%3Aindustrial&qf=TYPE%3A%22IMAGE%22&reusability=open](https://www.europeana.eu/en/search?page=1&qf=collection%3Aindustrial&qf=TYPE%3A%22IMAGE%22&reusability=open)

**3D data**: 
[https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%223D%22&qf=collection%3Aindustrial&query=&reusability=restricted&view=grid](https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%223D%22&qf=collection%3Aindustrial&query=&reusability=restricted&view=grid)  
[https://sketchfab.com/search?category=cultural-heritage-history&features=downloadable&licenses=7c23a1ba438d4306920229c12afcb5f9&licenses=322a749bcfa841b29dff1e8a1bb74b0b&q=industrial&type=models](https://sketchfab.com/search?category=cultural-heritage-history&features=downloadable&licenses=7c23a1ba438d4306920229c12afcb5f9&licenses=322a749bcfa841b29dff1e8a1bb74b0b&q=industrial&type=models)

**Videos**: 
[https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%22VIDEO%22&qf=collection%3Aindustrial&reusability=open](https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%22VIDEO%22&qf=collection%3Aindustrial&reusability=open)


### Crafts 

**Stories**: 
[https://www.europeana.eu/en/stories?tags=crafts](https://www.europeana.eu/en/stories?tags=crafts) 

**Images**: 
[https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%22IMAGE%22&query=craft&reusability=open&view=grid](https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%22IMAGE%22&query=craft&reusability=open&view=grid)

**3D data**: 
[https://sketchfab.com/search?category=cultural-heritage-history&features=downloadable&licenses=322a749bcfa841b29dff1e8a1bb74b0b&licenses=7c23a1ba438d4306920229c12afcb5f9&q=craft&type=models](https://sketchfab.com/search?category=cultural-heritage-history&features=downloadable&licenses=322a749bcfa841b29dff1e8a1bb74b0b&licenses=7c23a1ba438d4306920229c12afcb5f9&q=craft&type=models) 
[https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%223D%22&query=%22Craft%22&reusability=restricted&view=grid](https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%223D%22&query=%22Craft%22&reusability=restricted&view=grid)

**Videos**: 
[https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%22VIDEO%22&query=craft&reusability=open&view=grid](https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%22VIDEO%22&query=craft&reusability=open&view=grid)

### Photography

**Stories**: 
[https://www.europeana.eu/en/stories?tags=photography](https://www.europeana.eu/en/stories?tags=photography)

**Images**: 
[https://www.europeana.eu/en/search?page=1&qf=collection%3Aphotography&qf=TYPE%3A%22IMAGE%22&reusability=open%2Crestricted](https://www.europeana.eu/en/search?page=1&qf=collection%3Aphotography&qf=TYPE%3A%223D%22&reusability=open%2Crestricted)

**3D data**: 
[https://www.europeana.eu/en/search?page=1&qf=collection%3Aphotography&qf=TYPE%3A%223D%22&reusability=open%2Crestricted](https://www.europeana.eu/en/search?page=1&qf=collection%3Aphotography&qf=TYPE%3A%223D%22&reusability=open%2Crestricted)  

**Videos**: 
[https://www.europeana.eu/en/search?page=1&qf=collection%3Aphotography&qf=TYPE%3A%22VIDEO%22&reusability=open%2Crestricted](https://www.europeana.eu/en/search?page=1&qf=collection%3Aphotography&qf=TYPE%3A%22VIDEO%22&reusability=open%2Crestricted) 

### Fashion 

**Stories**: 
[https://www.europeana.eu/en/stories?tags=fashion](https://www.europeana.eu/en/stories?tags=fashion)

**Images**: 
[https://www.europeana.eu/en/search?page=1&qf=collection%3Afashion&qf=TYPE%3A%22IMAGE%22&reusability=restricted%2Copen](https://www.europeana.eu/en/search?page=1&qf=collection%3Afashion&qf=TYPE%3A%22IMAGE%22&reusability=restricted%2Copen)  

**3D data**: 
[https://sketchfab.com/search?category=cultural-heritage-history&features=downloadable&licenses=322a749bcfa841b29dff1e8a1bb74b0b&licenses=7c23a1ba438d4306920229c12afcb5f9&q=fashion&type=models](https://sketchfab.com/search?category=cultural-heritage-history&features=downloadable&licenses=322a749bcfa841b29dff1e8a1bb74b0b&licenses=7c23a1ba438d4306920229c12afcb5f9&q=fashion&type=models)

**Videos**: 
[https://www.europeana.eu/en/search?page=1&qf=collection%3Afashion&qf=TYPE%3A%22VIDEO%22&query=&view=grid](https://www.europeana.eu/en/search?page=1&qf=collection%3Afashion&qf=TYPE%3A%22VIDEO%22&query=&view=grid)


As a reminder, here are the sites with assets:

**Images**:
- [Pixabay](https://pixabay.com/)
- [Adobe Stock](https://stock.adobe.com/)
- [Shutterstock](https://www.shutterstock.com/)
- [Flickr](https://www.flickr.com/)

**Videos**:
- [YouTube](https://www.youtube.com)
- [Vimeo](https://vimeo.com/)
- [Wikimedia](https://commons.wikimedia.org/wiki/Category:Videos)

**3D Model**:

- [Sketchfab](https://sketchfab.com/)
- [Tinkercad](https://www.tinkercad.com/)
- [MorphoSource](https://www.morphosource.org/)
- [Kompakkt](https://kompakkt.de/home?locale=en)
- [Smithsonian 3D](https://3d.si.edu/)
- [Open Heritage 3D](https://openheritage3d.org/ )
- [Visual Media Service](https://visual.ariadne-infrastructure.eu/)

Others:

- [Europeana Platform](https://www.europeana.eu/en)
- [Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:Images)
- [Journal of Digital History Journal](https://journalofdigitalhistory.org/)
- [Brighton and Hove Museums](https://collections.brightonmuseums.org.uk/)
- [Victoria and Albert Museum](https://www.vam.ac.uk/collections?type=featured)
- [Science Group Museum](https://collection.sciencemuseumgroup.org.uk/)


