---
title: 'Storytelling with Mutltidimensional Media'
teaching: 10
exercises: 2
---


During this exercise you will curate a story bringing together multidimensional 
media using [Exhibit](https://www.exhibit.so/) tool.

The example below shows a story of the Kinora, which was an 
early motion picture device developed by the French inventors Auguste and Louis Lumière 
in 1895. 

The story brings together images, videos and 3D models to illustrate the
history of these artefacts, their context and mechanics. The media 
with which this story as developed is available [here](https://data.d4science.org/workspace-explorer-app?folderId=MUVkZVY5L1hRYnV4ZzJiUVljVlk5U1hmOHZYaDQ1SGVZT0l6aUZGa2lEclVFT0ppWEo4VDRzU2Z0alNiSk5GTg). 

You can also view the story
here: [https://www.exhibit.so/exhibits/zrHKbV2wqdpcRyfVW05M](https://www.exhibit.so/exhibits/zrHKbV2wqdpcRyfVW05M)

<iframe src="https://www.exhibit.so/exhibits/zrHKbV2wqdpcRyfVW05M?embedded=true" width="100%" height="600" allowfullscreen allow="autoplay" frameborder="0"></iframe>


## Developing a story in Exhibit
Using the dataset of multidimensional data
which you previously curated, the task is 
to create a story which brings all of this together.


Use the tutorial Exhibit website: [https://exhibit-culturedigitalskills.vercel.app/](https://exhibit-culturedigitalskills.vercel.app/)

You will need to register to use the tool.

Design a story 

